# -*- coding: utf-8 -*-
'''
Read Salt pillar data from a Palletjack YAML file
'''
from __future__ import absolute_import

# Don't "fix" the above docstring to put it on two lines, as the sphinx
# autosummary pulls only the first line for its description.

# Import python libs
import logging

# Import third party libs
import yaml

# Set up logging
log = logging.getLogger(__name__)


def ext_pillar(minion_id,
               pillar,  # pylint: disable=W0613
               path):
    '''
    Read pillar data from a Palletjack YAML file, itself generated by
    palletjack2salt.

    "path" is the path of the file, with the string "{environment}" to be
    replaced by the Salt environment and "{minion}" to be replaced by the
    minion ID.

    Matching Salt configuration:

      ext_pillar:
        - palletjack_yaml_file: /var/cache/palletjack/{environment}/{minion}.yaml
    '''

    real_path = path.format(environment = __opts__.get('environment'),
                            minion = minion_id)

    try:
        stream = file(real_path, 'r')
        return yaml.safe_load(stream)
    except Exception, e:
        log.critical(
                'Failed to load YAML data from {file}: {error}'.format(file = real_path, error = e)
                )
        return {}
