#!/usr/bin/env ruby

# Write configuration for the Kea DHCP server from a Palletjack warehouse

require 'palletjack'
require 'optparse'
require 'json'

options = {}

opts = OptionParser.new
opts.banner = "Usage: #{$PROGRAM_NAME} [options] <name> ...

Write configuration for the Kea DHCP server from a Palletjack warehouse

"
opts.on("-w DIR", "--warehouse DIR", "warehouse directory", String) {|dir| options[:warehouse] = dir }
opts.parse!

if not options[:warehouse]
  puts opts.to_s
  exit 1
end

jack = PalletJack.new(options[:warehouse])

kea_config = {"subnet4" => Array.new}

jack["ip_network"].each do |net|
  net_config = {"subnet" => "#{net['net.ip.cidr']}",
                "reservations" => [],
                "option-data" => []}
  if net['net.ip.gateway']
    net_config["option-data"] << {
      "name" => "routers",
      "code" => 3,
      "space" => "dhcp4",
      "csv-format" => true,
      "data" => "#{net['net.ip.gateway']}"
    }
  end

  jack["ip_interface",
       with_all:{"pallet.ip_network" =>
                 net['pallet.ip_network']}].each do |interface|
    net_config["reservations"] << [ {
      "hw-address" => "#{interface['net.mac.address']}",
      "ip-address" => "#{interface['net.ip.address']}",
      "hostname" => "#{interface['net.dns.fqdn']}"
    } ]
  end

  kea_config["subnet4"] << net_config
end

jj kea_config
