#!/usr/bin/env ruby

# Write configuration for the Kea DHCP server from a Palletjack warehouse

require 'palletjack'
require 'optparse'
require 'json'

options = {}

opts = OptionParser.new
opts.banner = "Usage: #{$PROGRAM_NAME} [options] <name> ...

Write configuration for the Kea DHCP server from a Palletjack warehouse

"
opts.on("-w DIR", "--warehouse DIR", "warehouse directory", String) {|dir| options[:warehouse] = dir }
opts.parse!

if not options[:warehouse]
  puts opts.to_s
  exit 1
end

jack = PalletJack.new(options[:warehouse])

kea_config = { "Dhcp4" => {
                 "interfaces-config" => { "interfaces" => [ '*' ] },
                 "lease-database" => { "type" => "memfile" },
                 "valid-lifetime" => 4000,
                 "subnet4" => Array.new
             }}

jack["ipv4_network"].each do |net|
  net_config = {"subnet" => "#{net['net.ipv4.cidr']}",
                "reservations" => [],
                "option-data" => []}
  if net['net.ipv4.gateway']
    net_config["option-data"] << {
      "name" => "routers",
      "code" => 3,
      "space" => "dhcp4",
      "csv-format" => true,
      "data" => "#{net['net.ipv4.gateway']}"
    }
  end

  if net['net.dns.resolver']
    resolvers = ""
    net['net.dns.resolver'].each do |resolver|
      resolvers << resolver << ", "
    end

    net_config["option-data"] << {
      "name" => "domain-name-servers",
      "code" => 6,
      "space" => "dhcp4",
      "csv-format" => true,
      "data" => resolvers.chomp(', ')
    }
  end

  jack["ipv4_interface",
       with_all:{"pallet.ipv4_network" =>
                 net['pallet.ipv4_network']}].each do |interface|
    net_config["reservations"] << {
      "hw-address" => "#{interface['net.mac.address']}",
      "ip-address" => "#{interface['net.ipv4.address']}",
      "hostname" => "#{interface['net.dns.fqdn']}"
    }
  end

  kea_config["Dhcp4"]["subnet4"] << net_config
end

jj kea_config
